#pragma once

enum class InputKey
{
	InputKey_SPACE = 0,
	InputKey_APOSTROPHE = 1,
	InputKey_COMMA = 2,
	InputKey_MINUS = 3,
	InputKey_PERIOD = 4,
	InputKey_SLASH = 5,
	InputKey_ZERO = 6,
	InputKey_ONE = 7,
	InputKey_TWO = 8,
	InputKey_THREE = 9,
	InputKey_FOUR = 10,
	InputKey_FIVE = 11,
	InputKey_SIX = 12,
	InputKey_SEVEN = 13,
	InputKey_EIGHT = 14,
	InputKey_NINE = 15,
	InputKey_SEMICOLON = 16,
	InputKey_EQUAL = 17,
	InputKey_A = 18,
	InputKey_B = 19,
	InputKey_C = 20,
	InputKey_D = 21,
	InputKey_E = 22,
	InputKey_F = 23,
	InputKey_G = 24,
	InputKey_H = 25,
	InputKey_I = 26,
	InputKey_J = 27,
	InputKey_K = 28,
	InputKey_L = 29,
	InputKey_M = 30,
	InputKey_N = 31,
	InputKey_O = 32,
	InputKey_P = 33,
	InputKey_Q = 34,
	InputKey_R = 35,
	InputKey_S = 36,
	InputKey_T = 37,
	InputKey_U = 38,
	InputKey_V = 39,
	InputKey_W = 40,
	InputKey_X = 41,
	InputKey_Y = 42,
	InputKey_Z = 43,
	InputKey_LEFT_BRACKET = 44,
	InputKey_BACKSLASH = 45,
	InputKey_RIGHT_BRACKET = 46,
	InputKey_GRAVE_ACCENT = 47,
	InputKey_WORLD_1 = 48,
	InputKey_WORLD_2 = 49,
	InputKey_ESCAPE = 50,
	InputKey_ENTER = 51,
	InputKey_TAB = 52,
	InputKey_BACKSPACE = 53,
	InputKey_INSERT = 54,
	InputKey_DELETE_2 = 55,
	InputKey_RIGHT = 56,
	InputKey_LEFT = 57,
	InputKey_DOWN = 58,
	InputKey_UP = 59,
	InputKey_PAGE_UP = 60,
	InputKey_PAGE_DOWN = 61,
	InputKey_HOME = 62,
	InputKey_END = 63,
	InputKey_CAPS_LOCK = 64,
	InputKey_SCROLL_LOCK = 65,
	InputKey_NUM_LOCK = 66,
	InputKey_PRINT_SCREEN = 67,
	InputKey_PAUSE = 68,
	InputKey_F1 = 69,
	InputKey_F2 = 70,
	InputKey_F3 = 71,
	InputKey_F4 = 72,
	InputKey_F5 = 73,
	InputKey_F6 = 74,
	InputKey_F7 = 75,
	InputKey_F8 = 76,
	InputKey_F9 = 77,
	InputKey_F10 = 78,
	InputKey_F11 = 79,
	InputKey_F12 = 80,
	InputKey_F13 = 81,
	InputKey_F14 = 82,
	InputKey_F15 = 83,
	InputKey_F16 = 84,
	InputKey_F17 = 85,
	InputKey_F18 = 86,
	InputKey_F19 = 87,
	InputKey_F20 = 88,
	InputKey_F21 = 89,
	InputKey_F22 = 90,
	InputKey_F23 = 91,
	InputKey_F24 = 92,
	InputKey_F25 = 93,
	InputKey_KP_ZERO = 94,
	InputKey_KP_ONE = 95,
	InputKey_KP_TWO = 96,
	InputKey_KP_THREE = 97,
	InputKey_KP_FOUR = 98,
	InputKey_KP_FIVE = 99,
	InputKey_KP_SIX = 100,
	InputKey_KP_SEVEN = 101,
	InputKey_KP_EIGHT = 102,
	InputKey_KP_NINE = 103,
	InputKey_KP_DECIMAL = 104,
	InputKey_KP_DIVIDE = 105,
	InputKey_KP_MULTIPLY = 106,
	InputKey_KP_SUBTRACT = 107,
	InputKey_KP_ADD = 108,
	InputKey_KP_ENTER = 109,
	InputKey_KP_EQUAL = 110,
	InputKey_LEFT_SHIFT = 111,
	InputKey_LEFT_CONTROL = 112,
	InputKey_LEFT_ALT = 113,
	InputKey_LEFT_SUPER = 114,
	InputKey_RIGHT_SHIFT = 115,
	InputKey_RIGHT_CONTROL = 116,
	InputKey_RIGHT_ALT = 117,
	InputKey_RIGHT_SUPER = 118,
	InputKey_MENU = 119,
	InputKey_MOUSE_BUTTON_1 = 120,
	InputKey_MOUSE_BUTTON_2 = 121,
	InputKey_MOUSE_BUTTON_3 = 122,
	InputKey_MOUSE_BUTTON_4 = 123,
	InputKey_MOUSE_BUTTON_5 = 124,
	InputKey_MOUSE_BUTTON_6 = 125,
	InputKey_MOUSE_BUTTON_7 = 126,
	InputKey_MOUSE_BUTTON_8 = 127,
	InputKey_MOUSE_BUTTON_LAST = 128,
	InputKey_MOUSE_BUTTON_LEFT = 129,
	InputKey_MOUSE_BUTTON_RIGHT = 130,
	InputKey_MOUSE_BUTTON_MIDDLE = 131,
	InputKey_LAST = 132,
};

enum class KeyState
{
	KeyStateFlag_NONE = 0,
	KeyStateFlag_PRESSED_THIS_FRAME = 1,
	KeyStateFlag_PRESSED = 2,
	KeyStateFlag_RELEASED_THIS_FRAME = 4,
	KeyStateFlag_KEY_DOWN = (KeyStateFlag_PRESSED_THIS_FRAME | KeyStateFlag_PRESSED),
	KeyStateFlag_KEY_UP = (KeyStateFlag_RELEASED_THIS_FRAME | KeyStateFlag_NONE),
};

struct InputHandle
{
	void* handle = nullptr;
	void allocate(void* p_window);
	void free();

	void new_frame();
	bool get_state(InputKey p_key, KeyState p_state);

};