#pragma once

#define CONFIGURATION_DEBUG 0
#define CONFIGURATION_RELEASE_DEBUG 1
#define CONFIGURATION_RELEASE 2

#ifndef CONFIGURATION_TYPE
#define CONFIGURATION_TYPE CONFIGURATION_DEBUG
#endif

#if CONFIGURATION_TYPE == CONFIGURATION_DEBUG

#define CONTAINER_BOUND_TEST 1
#define CONTAINER_MEMORY_TEST 1
#define SCENE_BOUND_TEST 1
#define RENDER_BOUND_TEST 1
#define COLLIDER_BOUND_TEST 1
#define STANDARD_ALLOCATION_BOUND_TEST 1
#define USE_OPTICK 0

#elif CONFIGURATION_TYPE == CONFIGURATION_RELEASE_DEBUG

#define CONTAINER_BOUND_TEST 1
#define CONTAINER_MEMORY_TEST 1
#define SCENE_BOUND_TEST 1
#define RENDER_BOUND_TEST 1
#define COLLIDER_BOUND_TEST 1
#define STANDARD_ALLOCATION_BOUND_TEST 1
#define USE_OPTICK 0

#elif CONFIGURATION_TYPE == CONFIGURATION_RELEASE

#define CONTAINER_BOUND_TEST 0
#define CONTAINER_MEMORY_TEST 0
#define SCENE_BOUND_TEST 0
#define RENDER_BOUND_TEST 0
#define COLLIDER_BOUND_TEST 0
#define STANDARD_ALLOCATION_BOUND_TEST 0
#define USE_OPTICK 0

#endif